// Projects the world once, at build time, so no browser ever loads d3.
//
// The 110m outlines are a fixed thing: they do not change between deploys and
// they do not depend on anything a visitor did. Projecting them in the browser
// would mean shipping d3-geo and topojson-client to read a file that answers
// the same way every time. This writes the answer instead, as path strings plus
// the scale and translate a dot needs to land in the same place.
//
// Antarctica is dropped. It is six kilobytes of coastline and it has never had
// a visitor.
import { geoPath, geoNaturalEarth1 } from 'd3-geo';
import { feature } from 'topojson-client';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../src/map/world.generated.ts');

// The drawing's own size. Wide and short, because a world map that reserves
// room for the poles reserves room for nothing: the top and bottom eighths of
// Natural Earth are ice and empty ocean.
const WIDTH = 960;
const HEIGHT = 420;
const ANTARCTICA = '010';

const topology = JSON.parse(readFileSync(require.resolve('world-atlas/countries-110m.json'), 'utf8'));
const countries = feature(topology, topology.objects.countries);
const drawn = countries.features.filter((country) => country.id !== ANTARCTICA);

// Fitted to the countries that are left, so dropping Antarctica actually buys
// the space rather than leaving a gap where it was.
const projection = geoNaturalEarth1().fitSize([WIDTH, HEIGHT], {
  type: 'FeatureCollection',
  features: drawn,
});
const path = geoPath(projection);

// One decimal, which is a tenth of a pixel on a 960 unit drawing and a fifth of
// the bytes the default seventeen decimals cost. Measured: 60 KB gzipped at
// three decimals, 40 at one, and at a width no screenshot will ever exceed the
// difference is invisible.
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n) * 10) / 10));

const shapes = drawn
  .map((country) => ({ id: String(country.id), d: round(path(country) ?? '') }))
  .filter((shape) => shape.d !== '');

const [translateX, translateY] = projection.translate();

const file = `// Generated by scripts/build-world.mjs. Do not edit.
//
// The 110m world outlines, projected once with Natural Earth 1 and written as
// path strings, so no browser loads d3 to draw a file that never changes.
// Antarctica is not here: six kilobytes of coastline that has never had a
// visitor.
//
// The scale and translate below are the ones these paths were drawn with, and
// they are what project() in ./naturalEarth.ts needs to put a dot in the same
// place the outlines are. Two projections is how a dot lands in the sea beside
// the country it belongs to.
import type { Projection } from './naturalEarth.js';

export const WORLD: Projection = {
  width: ${WIDTH},
  height: ${HEIGHT},
  scale: ${Math.round(projection.scale() * 1e6) / 1e6},
  translate: [${Math.round(translateX * 1e6) / 1e6}, ${Math.round(translateY * 1e6) / 1e6}],
};

// One entry per country, keyed by its numeric code. Nothing reads the key yet:
// it is here so a choropleth can join on it without regenerating the file.
export const SHAPES: readonly { id: string; d: string }[] = [
${shapes.map((shape) => `  { id: '${shape.id}', d: '${shape.d}' },`).join('\n')}
];
`;

writeFileSync(out, file);
console.warn(
  `world.generated.ts: ${shapes.length} countries, ${Math.round(file.length / 1024)} KB`,
);
